// components/Navbar.vue
<template>
    <div class="flex flex-wrap bg-blue-400 w-full h-10 navbar">
        <div class="col">
            <NuxtLink to="/" class="ease duration-700 hover:bg-blue-500 p-3 inline-block py-2 px-5">
                Home
            </NuxtLink>
        </div>
        <div class="col">
            <NuxtLink to="/user/9gr" class="ease duration-700 hover:bg-blue-500 p-3 inline-block py-2 px-5">
                Signature History
            </NuxtLink>
        </div>
    </div>
</template>
<script>
export default {
    
}
</script>

// src/lib/Navbar.svelte
<div class="flex flex-wrap bg-blue-400 w-full h-10 navbar">
    <div class="col">
        <a href="/" class="ease duration-700 hover:bg-blue-500 p-3 inline-block py-2 px-5">
            Scratory
        </a>
    </div>
    <div class="col">
        <a href="/user/Verixion" class="ease duration-700 hover:bg-blue-500 p-3 inline-block py-2 px-5">
            Signatures
        </a>
    </div>
    <div class="col">
        <a href="/cloud/43" class="ease duration-700 hover:bg-blue-500 p-3 inline-block py-2 px-5">
            Cloud data
        </a>
    </div>
</div>
